/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AppBrandBookRouteImport } from './routes/_app.brand-book'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOrdensServicoRouteImport } from './routes/_app.ordens-servico'
import { Route as AppPagamentosRouteImport } from './routes/_app.pagamentos'
import { Route as AppPetsRouteImport } from './routes/_app.pets'
import { Route as AppServicosProdutosRouteImport } from './routes/_app.servicos-produtos'
import { Route as AppTutoresRouteImport } from './routes/_app.tutores'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/_app.configuracoes.index'
import { Route as AppConfiguracoesEspeciesRouteImport } from './routes/_app.configuracoes.especies'
import { Route as AppConfiguracoesModalidadesRouteImport } from './routes/_app.configuracoes.modalidades'
import { Route as AppConfiguracoesRacasRouteImport } from './routes/_app.configuracoes.racas'
import { Route as AppConfiguracoesUsuariosRouteImport } from './routes/_app.configuracoes.usuarios'
import { Route as AppContratosIndexRouteImport } from './routes/_app.contratos.index'
import { Route as AppContratosIdRouteImport } from './routes/_app.contratos.$id'
import { Route as AppContratosNovoRouteImport } from './routes/_app.contratos.novo'
import { Route as AppObitosNovoRouteImport } from './routes/_app.obitos.novo'
import { Route as AppOrdensServicoIndexRouteImport } from './routes/_app.ordens-servico.index'
import { Route as AppOrdensServicoIdRouteImport } from './routes/_app.ordens-servico.$id'
import { Route as AppPagamentosIndexRouteImport } from './routes/_app.pagamentos.index'
import { Route as AppPagamentosIdRouteImport } from './routes/_app.pagamentos.$id'
import { Route as AppPetsIndexRouteImport } from './routes/_app.pets.index'
import { Route as AppPetsIdRouteImport } from './routes/_app.pets.$id'
import { Route as AppPetsNovoRouteImport } from './routes/_app.pets.novo'
import { Route as AppServicosProdutosIndexRouteImport } from './routes/_app.servicos-produtos.index'
import { Route as AppServicosProdutosNovoRouteImport } from './routes/_app.servicos-produtos.novo'
import { Route as AppTutoresIndexRouteImport } from './routes/_app.tutores.index'
import { Route as AppTutoresIdRouteImport } from './routes/_app.tutores.$id'
import { Route as AppTutoresNovoRouteImport } from './routes/_app.tutores.novo'
import { Route as AppPetsIdIndexRouteImport } from './routes/_app.pets.$id.index'
import { Route as AppPetsIdEditarRouteImport } from './routes/_app.pets.$id.editar'
import { Route as AppServicosProdutosIdEditarRouteImport } from './routes/_app.servicos-produtos.$id.editar'
import { Route as AppTutoresIdIndexRouteImport } from './routes/_app.tutores.$id.index'
import { Route as AppTutoresIdEditarRouteImport } from './routes/_app.tutores.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandBookRoute = AppBrandBookRouteImport.update({
  id: '/brand-book',
  path: '/brand-book',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoRoute = AppOrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsRoute = AppPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosProdutosRoute = AppServicosProdutosRouteImport.update({
  id: '/servicos-produtos',
  path: '/servicos-produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppTutoresRoute = AppTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesEspeciesRoute =
  AppConfiguracoesEspeciesRouteImport.update({
    id: '/especies',
    path: '/especies',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesModalidadesRoute =
  AppConfiguracoesModalidadesRouteImport.update({
    id: '/modalidades',
    path: '/modalidades',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesRacasRoute = AppConfiguracoesRacasRouteImport.update({
  id: '/racas',
  path: '/racas',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesUsuariosRoute =
  AppConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContratosRoute,
} as any)
const AppContratosIdRoute = AppContratosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContratosRoute,
} as any)
const AppContratosNovoRoute = AppContratosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppContratosRoute,
} as any)
const AppObitosNovoRoute = AppObitosNovoRouteImport.update({
  id: '/obitos/novo',
  path: '/obitos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoIndexRoute = AppOrdensServicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdensServicoRoute,
} as any)
const AppOrdensServicoIdRoute = AppOrdensServicoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdensServicoRoute,
} as any)
const AppPagamentosIndexRoute = AppPagamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPagamentosRoute,
} as any)
const AppPagamentosIdRoute = AppPagamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPagamentosRoute,
} as any)
const AppPetsIndexRoute = AppPetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPetsRoute,
} as any)
const AppPetsIdRoute = AppPetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPetsRoute,
} as any)
const AppPetsNovoRoute = AppPetsNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppPetsRoute,
} as any)
const AppServicosProdutosIndexRoute =
  AppServicosProdutosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServicosProdutosRoute,
  } as any)
const AppServicosProdutosNovoRoute = AppServicosProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppServicosProdutosRoute,
} as any)
const AppTutoresIndexRoute = AppTutoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTutoresRoute,
} as any)
const AppTutoresIdRoute = AppTutoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTutoresRoute,
} as any)
const AppTutoresNovoRoute = AppTutoresNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppTutoresRoute,
} as any)
const AppPetsIdIndexRoute = AppPetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPetsIdRoute,
} as any)
const AppPetsIdEditarRoute = AppPetsIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppPetsIdRoute,
} as any)
const AppServicosProdutosIdEditarRoute =
  AppServicosProdutosIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AppServicosProdutosRoute,
  } as any)
const AppTutoresIdIndexRoute = AppTutoresIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTutoresIdRoute,
} as any)
const AppTutoresIdEditarRoute = AppTutoresIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppTutoresIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/brand-book': typeof AppBrandBookRoute
  '/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/contratos': typeof AppContratosRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/ordens-servico': typeof AppOrdensServicoRouteWithChildren
  '/pagamentos': typeof AppPagamentosRouteWithChildren
  '/pets': typeof AppPetsRouteWithChildren
  '/servicos-produtos': typeof AppServicosProdutosRouteWithChildren
  '/tutores': typeof AppTutoresRouteWithChildren
  '/configuracoes/especies': typeof AppConfiguracoesEspeciesRoute
  '/configuracoes/modalidades': typeof AppConfiguracoesModalidadesRoute
  '/configuracoes/racas': typeof AppConfiguracoesRacasRoute
  '/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/obitos/novo': typeof AppObitosNovoRoute
  '/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/pagamentos/$id': typeof AppPagamentosIdRoute
  '/pets/$id': typeof AppPetsIdRouteWithChildren
  '/pets/novo': typeof AppPetsNovoRoute
  '/servicos-produtos/novo': typeof AppServicosProdutosNovoRoute
  '/tutores/$id': typeof AppTutoresIdRouteWithChildren
  '/tutores/novo': typeof AppTutoresNovoRoute
  '/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/ordens-servico/': typeof AppOrdensServicoIndexRoute
  '/pagamentos/': typeof AppPagamentosIndexRoute
  '/pets/': typeof AppPetsIndexRoute
  '/servicos-produtos/': typeof AppServicosProdutosIndexRoute
  '/tutores/': typeof AppTutoresIndexRoute
  '/pets/$id/editar': typeof AppPetsIdEditarRoute
  '/servicos-produtos/$id/editar': typeof AppServicosProdutosIdEditarRoute
  '/tutores/$id/editar': typeof AppTutoresIdEditarRoute
  '/pets/$id/': typeof AppPetsIdIndexRoute
  '/tutores/$id/': typeof AppTutoresIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/brand-book': typeof AppBrandBookRoute
  '/dashboard': typeof AppDashboardRoute
  '/configuracoes/especies': typeof AppConfiguracoesEspeciesRoute
  '/configuracoes/modalidades': typeof AppConfiguracoesModalidadesRoute
  '/configuracoes/racas': typeof AppConfiguracoesRacasRoute
  '/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/obitos/novo': typeof AppObitosNovoRoute
  '/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/pagamentos/$id': typeof AppPagamentosIdRoute
  '/pets/novo': typeof AppPetsNovoRoute
  '/servicos-produtos/novo': typeof AppServicosProdutosNovoRoute
  '/tutores/novo': typeof AppTutoresNovoRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/contratos': typeof AppContratosIndexRoute
  '/ordens-servico': typeof AppOrdensServicoIndexRoute
  '/pagamentos': typeof AppPagamentosIndexRoute
  '/pets': typeof AppPetsIndexRoute
  '/servicos-produtos': typeof AppServicosProdutosIndexRoute
  '/tutores': typeof AppTutoresIndexRoute
  '/pets/$id/editar': typeof AppPetsIdEditarRoute
  '/servicos-produtos/$id/editar': typeof AppServicosProdutosIdEditarRoute
  '/tutores/$id/editar': typeof AppTutoresIdEditarRoute
  '/pets/$id': typeof AppPetsIdIndexRoute
  '/tutores/$id': typeof AppTutoresIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/brand-book': typeof AppBrandBookRoute
  '/_app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/_app/contratos': typeof AppContratosRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ordens-servico': typeof AppOrdensServicoRouteWithChildren
  '/_app/pagamentos': typeof AppPagamentosRouteWithChildren
  '/_app/pets': typeof AppPetsRouteWithChildren
  '/_app/servicos-produtos': typeof AppServicosProdutosRouteWithChildren
  '/_app/tutores': typeof AppTutoresRouteWithChildren
  '/_app/configuracoes/especies': typeof AppConfiguracoesEspeciesRoute
  '/_app/configuracoes/modalidades': typeof AppConfiguracoesModalidadesRoute
  '/_app/configuracoes/racas': typeof AppConfiguracoesRacasRoute
  '/_app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/_app/contratos/$id': typeof AppContratosIdRoute
  '/_app/contratos/novo': typeof AppContratosNovoRoute
  '/_app/obitos/novo': typeof AppObitosNovoRoute
  '/_app/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/_app/pagamentos/$id': typeof AppPagamentosIdRoute
  '/_app/pets/$id': typeof AppPetsIdRouteWithChildren
  '/_app/pets/novo': typeof AppPetsNovoRoute
  '/_app/servicos-produtos/novo': typeof AppServicosProdutosNovoRoute
  '/_app/tutores/$id': typeof AppTutoresIdRouteWithChildren
  '/_app/tutores/novo': typeof AppTutoresNovoRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/ordens-servico/': typeof AppOrdensServicoIndexRoute
  '/_app/pagamentos/': typeof AppPagamentosIndexRoute
  '/_app/pets/': typeof AppPetsIndexRoute
  '/_app/servicos-produtos/': typeof AppServicosProdutosIndexRoute
  '/_app/tutores/': typeof AppTutoresIndexRoute
  '/_app/pets/$id/editar': typeof AppPetsIdEditarRoute
  '/_app/servicos-produtos/$id/editar': typeof AppServicosProdutosIdEditarRoute
  '/_app/tutores/$id/editar': typeof AppTutoresIdEditarRoute
  '/_app/pets/$id/': typeof AppPetsIdIndexRoute
  '/_app/tutores/$id/': typeof AppTutoresIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/brand-book'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/ordens-servico'
    | '/pagamentos'
    | '/pets'
    | '/servicos-produtos'
    | '/tutores'
    | '/configuracoes/especies'
    | '/configuracoes/modalidades'
    | '/configuracoes/racas'
    | '/configuracoes/usuarios'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/obitos/novo'
    | '/ordens-servico/$id'
    | '/pagamentos/$id'
    | '/pets/$id'
    | '/pets/novo'
    | '/servicos-produtos/novo'
    | '/tutores/$id'
    | '/tutores/novo'
    | '/configuracoes/'
    | '/contratos/'
    | '/ordens-servico/'
    | '/pagamentos/'
    | '/pets/'
    | '/servicos-produtos/'
    | '/tutores/'
    | '/pets/$id/editar'
    | '/servicos-produtos/$id/editar'
    | '/tutores/$id/editar'
    | '/pets/$id/'
    | '/tutores/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/brand-book'
    | '/dashboard'
    | '/configuracoes/especies'
    | '/configuracoes/modalidades'
    | '/configuracoes/racas'
    | '/configuracoes/usuarios'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/obitos/novo'
    | '/ordens-servico/$id'
    | '/pagamentos/$id'
    | '/pets/novo'
    | '/servicos-produtos/novo'
    | '/tutores/novo'
    | '/configuracoes'
    | '/contratos'
    | '/ordens-servico'
    | '/pagamentos'
    | '/pets'
    | '/servicos-produtos'
    | '/tutores'
    | '/pets/$id/editar'
    | '/servicos-produtos/$id/editar'
    | '/tutores/$id/editar'
    | '/pets/$id'
    | '/tutores/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/unauthorized'
    | '/_app/brand-book'
    | '/_app/configuracoes'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/ordens-servico'
    | '/_app/pagamentos'
    | '/_app/pets'
    | '/_app/servicos-produtos'
    | '/_app/tutores'
    | '/_app/configuracoes/especies'
    | '/_app/configuracoes/modalidades'
    | '/_app/configuracoes/racas'
    | '/_app/configuracoes/usuarios'
    | '/_app/contratos/$id'
    | '/_app/contratos/novo'
    | '/_app/obitos/novo'
    | '/_app/ordens-servico/$id'
    | '/_app/pagamentos/$id'
    | '/_app/pets/$id'
    | '/_app/pets/novo'
    | '/_app/servicos-produtos/novo'
    | '/_app/tutores/$id'
    | '/_app/tutores/novo'
    | '/_app/configuracoes/'
    | '/_app/contratos/'
    | '/_app/ordens-servico/'
    | '/_app/pagamentos/'
    | '/_app/pets/'
    | '/_app/servicos-produtos/'
    | '/_app/tutores/'
    | '/_app/pets/$id/editar'
    | '/_app/servicos-produtos/$id/editar'
    | '/_app/tutores/$id/editar'
    | '/_app/pets/$id/'
    | '/_app/tutores/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/brand-book': {
      id: '/_app/brand-book'
      path: '/brand-book'
      fullPath: '/brand-book'
      preLoaderRoute: typeof AppBrandBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico': {
      id: '/_app/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AppOrdensServicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagamentos': {
      id: '/_app/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pets': {
      id: '/_app/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AppPetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicos-produtos': {
      id: '/_app/servicos-produtos'
      path: '/servicos-produtos'
      fullPath: '/servicos-produtos'
      preLoaderRoute: typeof AppServicosProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutores': {
      id: '/_app/tutores'
      path: '/tutores'
      fullPath: '/tutores'
      preLoaderRoute: typeof AppTutoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/especies': {
      id: '/_app/configuracoes/especies'
      path: '/especies'
      fullPath: '/configuracoes/especies'
      preLoaderRoute: typeof AppConfiguracoesEspeciesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/modalidades': {
      id: '/_app/configuracoes/modalidades'
      path: '/modalidades'
      fullPath: '/configuracoes/modalidades'
      preLoaderRoute: typeof AppConfiguracoesModalidadesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/racas': {
      id: '/_app/configuracoes/racas'
      path: '/racas'
      fullPath: '/configuracoes/racas'
      preLoaderRoute: typeof AppConfiguracoesRacasRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/usuarios': {
      id: '/_app/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AppConfiguracoesUsuariosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppContratosRoute
    }
    '/_app/contratos/$id': {
      id: '/_app/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AppContratosIdRouteImport
      parentRoute: typeof AppContratosRoute
    }
    '/_app/contratos/novo': {
      id: '/_app/contratos/novo'
      path: '/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AppContratosNovoRouteImport
      parentRoute: typeof AppContratosRoute
    }
    '/_app/obitos/novo': {
      id: '/_app/obitos/novo'
      path: '/obitos/novo'
      fullPath: '/obitos/novo'
      preLoaderRoute: typeof AppObitosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico/': {
      id: '/_app/ordens-servico/'
      path: '/'
      fullPath: '/ordens-servico/'
      preLoaderRoute: typeof AppOrdensServicoIndexRouteImport
      parentRoute: typeof AppOrdensServicoRoute
    }
    '/_app/ordens-servico/$id': {
      id: '/_app/ordens-servico/$id'
      path: '/$id'
      fullPath: '/ordens-servico/$id'
      preLoaderRoute: typeof AppOrdensServicoIdRouteImport
      parentRoute: typeof AppOrdensServicoRoute
    }
    '/_app/pagamentos/': {
      id: '/_app/pagamentos/'
      path: '/'
      fullPath: '/pagamentos/'
      preLoaderRoute: typeof AppPagamentosIndexRouteImport
      parentRoute: typeof AppPagamentosRoute
    }
    '/_app/pagamentos/$id': {
      id: '/_app/pagamentos/$id'
      path: '/$id'
      fullPath: '/pagamentos/$id'
      preLoaderRoute: typeof AppPagamentosIdRouteImport
      parentRoute: typeof AppPagamentosRoute
    }
    '/_app/pets/': {
      id: '/_app/pets/'
      path: '/'
      fullPath: '/pets/'
      preLoaderRoute: typeof AppPetsIndexRouteImport
      parentRoute: typeof AppPetsRoute
    }
    '/_app/pets/$id': {
      id: '/_app/pets/$id'
      path: '/$id'
      fullPath: '/pets/$id'
      preLoaderRoute: typeof AppPetsIdRouteImport
      parentRoute: typeof AppPetsRoute
    }
    '/_app/pets/novo': {
      id: '/_app/pets/novo'
      path: '/novo'
      fullPath: '/pets/novo'
      preLoaderRoute: typeof AppPetsNovoRouteImport
      parentRoute: typeof AppPetsRoute
    }
    '/_app/servicos-produtos/': {
      id: '/_app/servicos-produtos/'
      path: '/'
      fullPath: '/servicos-produtos/'
      preLoaderRoute: typeof AppServicosProdutosIndexRouteImport
      parentRoute: typeof AppServicosProdutosRoute
    }
    '/_app/servicos-produtos/novo': {
      id: '/_app/servicos-produtos/novo'
      path: '/novo'
      fullPath: '/servicos-produtos/novo'
      preLoaderRoute: typeof AppServicosProdutosNovoRouteImport
      parentRoute: typeof AppServicosProdutosRoute
    }
    '/_app/tutores/': {
      id: '/_app/tutores/'
      path: '/'
      fullPath: '/tutores/'
      preLoaderRoute: typeof AppTutoresIndexRouteImport
      parentRoute: typeof AppTutoresRoute
    }
    '/_app/tutores/$id': {
      id: '/_app/tutores/$id'
      path: '/$id'
      fullPath: '/tutores/$id'
      preLoaderRoute: typeof AppTutoresIdRouteImport
      parentRoute: typeof AppTutoresRoute
    }
    '/_app/tutores/novo': {
      id: '/_app/tutores/novo'
      path: '/novo'
      fullPath: '/tutores/novo'
      preLoaderRoute: typeof AppTutoresNovoRouteImport
      parentRoute: typeof AppTutoresRoute
    }
    '/_app/pets/$id/': {
      id: '/_app/pets/$id/'
      path: '/'
      fullPath: '/pets/$id/'
      preLoaderRoute: typeof AppPetsIdIndexRouteImport
      parentRoute: typeof AppPetsIdRoute
    }
    '/_app/pets/$id/editar': {
      id: '/_app/pets/$id/editar'
      path: '/editar'
      fullPath: '/pets/$id/editar'
      preLoaderRoute: typeof AppPetsIdEditarRouteImport
      parentRoute: typeof AppPetsIdRoute
    }
    '/_app/servicos-produtos/$id/editar': {
      id: '/_app/servicos-produtos/$id/editar'
      path: '/$id/editar'
      fullPath: '/servicos-produtos/$id/editar'
      preLoaderRoute: typeof AppServicosProdutosIdEditarRouteImport
      parentRoute: typeof AppServicosProdutosRoute
    }
    '/_app/tutores/$id/': {
      id: '/_app/tutores/$id/'
      path: '/'
      fullPath: '/tutores/$id/'
      preLoaderRoute: typeof AppTutoresIdIndexRouteImport
      parentRoute: typeof AppTutoresIdRoute
    }
    '/_app/tutores/$id/editar': {
      id: '/_app/tutores/$id/editar'
      path: '/editar'
      fullPath: '/tutores/$id/editar'
      preLoaderRoute: typeof AppTutoresIdEditarRouteImport
      parentRoute: typeof AppTutoresIdRoute
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesEspeciesRoute: typeof AppConfiguracoesEspeciesRoute
  AppConfiguracoesModalidadesRoute: typeof AppConfiguracoesModalidadesRoute
  AppConfiguracoesRacasRoute: typeof AppConfiguracoesRacasRoute
  AppConfiguracoesUsuariosRoute: typeof AppConfiguracoesUsuariosRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesEspeciesRoute: AppConfiguracoesEspeciesRoute,
  AppConfiguracoesModalidadesRoute: AppConfiguracoesModalidadesRoute,
  AppConfiguracoesRacasRoute: AppConfiguracoesRacasRoute,
  AppConfiguracoesUsuariosRoute: AppConfiguracoesUsuariosRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppContratosRouteChildren {
  AppContratosIdRoute: typeof AppContratosIdRoute
  AppContratosNovoRoute: typeof AppContratosNovoRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
}

const AppContratosRouteChildren: AppContratosRouteChildren = {
  AppContratosIdRoute: AppContratosIdRoute,
  AppContratosNovoRoute: AppContratosNovoRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
}

const AppContratosRouteWithChildren = AppContratosRoute._addFileChildren(
  AppContratosRouteChildren,
)

interface AppOrdensServicoRouteChildren {
  AppOrdensServicoIdRoute: typeof AppOrdensServicoIdRoute
  AppOrdensServicoIndexRoute: typeof AppOrdensServicoIndexRoute
}

const AppOrdensServicoRouteChildren: AppOrdensServicoRouteChildren = {
  AppOrdensServicoIdRoute: AppOrdensServicoIdRoute,
  AppOrdensServicoIndexRoute: AppOrdensServicoIndexRoute,
}

const AppOrdensServicoRouteWithChildren =
  AppOrdensServicoRoute._addFileChildren(AppOrdensServicoRouteChildren)

interface AppPagamentosRouteChildren {
  AppPagamentosIdRoute: typeof AppPagamentosIdRoute
  AppPagamentosIndexRoute: typeof AppPagamentosIndexRoute
}

const AppPagamentosRouteChildren: AppPagamentosRouteChildren = {
  AppPagamentosIdRoute: AppPagamentosIdRoute,
  AppPagamentosIndexRoute: AppPagamentosIndexRoute,
}

const AppPagamentosRouteWithChildren = AppPagamentosRoute._addFileChildren(
  AppPagamentosRouteChildren,
)

interface AppPetsIdRouteChildren {
  AppPetsIdEditarRoute: typeof AppPetsIdEditarRoute
  AppPetsIdIndexRoute: typeof AppPetsIdIndexRoute
}

const AppPetsIdRouteChildren: AppPetsIdRouteChildren = {
  AppPetsIdEditarRoute: AppPetsIdEditarRoute,
  AppPetsIdIndexRoute: AppPetsIdIndexRoute,
}

const AppPetsIdRouteWithChildren = AppPetsIdRoute._addFileChildren(
  AppPetsIdRouteChildren,
)

interface AppPetsRouteChildren {
  AppPetsIdRoute: typeof AppPetsIdRouteWithChildren
  AppPetsNovoRoute: typeof AppPetsNovoRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
}

const AppPetsRouteChildren: AppPetsRouteChildren = {
  AppPetsIdRoute: AppPetsIdRouteWithChildren,
  AppPetsNovoRoute: AppPetsNovoRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
}

const AppPetsRouteWithChildren =
  AppPetsRoute._addFileChildren(AppPetsRouteChildren)

interface AppServicosProdutosRouteChildren {
  AppServicosProdutosNovoRoute: typeof AppServicosProdutosNovoRoute
  AppServicosProdutosIndexRoute: typeof AppServicosProdutosIndexRoute
  AppServicosProdutosIdEditarRoute: typeof AppServicosProdutosIdEditarRoute
}

const AppServicosProdutosRouteChildren: AppServicosProdutosRouteChildren = {
  AppServicosProdutosNovoRoute: AppServicosProdutosNovoRoute,
  AppServicosProdutosIndexRoute: AppServicosProdutosIndexRoute,
  AppServicosProdutosIdEditarRoute: AppServicosProdutosIdEditarRoute,
}

const AppServicosProdutosRouteWithChildren =
  AppServicosProdutosRoute._addFileChildren(AppServicosProdutosRouteChildren)

interface AppTutoresIdRouteChildren {
  AppTutoresIdEditarRoute: typeof AppTutoresIdEditarRoute
  AppTutoresIdIndexRoute: typeof AppTutoresIdIndexRoute
}

const AppTutoresIdRouteChildren: AppTutoresIdRouteChildren = {
  AppTutoresIdEditarRoute: AppTutoresIdEditarRoute,
  AppTutoresIdIndexRoute: AppTutoresIdIndexRoute,
}

const AppTutoresIdRouteWithChildren = AppTutoresIdRoute._addFileChildren(
  AppTutoresIdRouteChildren,
)

interface AppTutoresRouteChildren {
  AppTutoresIdRoute: typeof AppTutoresIdRouteWithChildren
  AppTutoresNovoRoute: typeof AppTutoresNovoRoute
  AppTutoresIndexRoute: typeof AppTutoresIndexRoute
}

const AppTutoresRouteChildren: AppTutoresRouteChildren = {
  AppTutoresIdRoute: AppTutoresIdRouteWithChildren,
  AppTutoresNovoRoute: AppTutoresNovoRoute,
  AppTutoresIndexRoute: AppTutoresIndexRoute,
}

const AppTutoresRouteWithChildren = AppTutoresRoute._addFileChildren(
  AppTutoresRouteChildren,
)

interface AppRouteChildren {
  AppBrandBookRoute: typeof AppBrandBookRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppContratosRoute: typeof AppContratosRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrdensServicoRoute: typeof AppOrdensServicoRouteWithChildren
  AppPagamentosRoute: typeof AppPagamentosRouteWithChildren
  AppPetsRoute: typeof AppPetsRouteWithChildren
  AppServicosProdutosRoute: typeof AppServicosProdutosRouteWithChildren
  AppTutoresRoute: typeof AppTutoresRouteWithChildren
  AppObitosNovoRoute: typeof AppObitosNovoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrandBookRoute: AppBrandBookRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppContratosRoute: AppContratosRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOrdensServicoRoute: AppOrdensServicoRouteWithChildren,
  AppPagamentosRoute: AppPagamentosRouteWithChildren,
  AppPetsRoute: AppPetsRouteWithChildren,
  AppServicosProdutosRoute: AppServicosProdutosRouteWithChildren,
  AppTutoresRoute: AppTutoresRouteWithChildren,
  AppObitosNovoRoute: AppObitosNovoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
